{{- if or .Values.auth.database (and .Values.auth.username .Values.auth.password) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-init
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  01-create-user.sql: |
    {{- if .Values.auth.database }}
    CREATE DATABASE "${CUSTOM_DB}";
    {{- end }}
    {{- if and .Values.auth.username .Values.auth.password }}
    CREATE USER "${CUSTOM_USER}" WITH PASSWORD '${CUSTOM_PASSWORD}';
    {{- end }}
    {{- if and .Values.auth.database .Values.auth.username .Values.auth.password }}
    GRANT ALL PRIVILEGES ON DATABASE "${CUSTOM_DB}" TO "${CUSTOM_USER}";
    {{- end }}
{{- end }}